// Generated by Wrangler on Sat Jul 06 2024 02:21:35 GMT+0100 (West Africa Standard Time)
// by running `wrangler types`

interface Env {
	DB_NAME: "postgres";
	DB_USERNAME: "postgres.dmyldrxpkkrkktmqjrwr";
	DB_HOST: "aws-0-eu-central-1.pooler.supabase.com";
	DB_PORT: 6543;
	JWT_SECRET: "supersecret";
	JWT_PASSPHRASE: "super_passphrase";
	JWT_EXPIRES_IN: "1d";
	DB_PASSWORD: string;
}
